### ISSUE TITLE
Rendering of Branch-annotation-repo-HOWTO is very messed up with the conversion from .md to .Rmd

### ISSUE THREAD

**Issue by lshep** [Bioconductor/ReleaseLaunch#8]
Either convert back or fix. 
The rendering and spacing got very messed up

**Comment by lshep** [comment]
We actually had to pull up the history and look at the old file in order to branch the annotations and get the correct commands.

**Comment by LiNk-NY** [comment]
Can you be more specific and provide examples? 

I noticed a couple of commands with extra carriage returns. I have fixed those. 
Other than that they have not changed. 
I did add  infobox highlighting for important notes. Other spacing differences are due to `BiocStyle` styling. 

If you're referring to the [`pkgdown` version](https://bioconductor.github.io/ReleaseLaunch/articles/Branch-annotation-repo-HOWTO.html), `pkgdown` doesn't have an option for numbered sections unless it is rendered "as-is". The `BiocStyle` version does which can be seen with `browseVignettes`.

**Comment by Kayla-Morrell** [comment]
@LiNk-NY - Here are a couple examples, the last being the biggest issue when doing the branching.

Line 111 and 112 in the current version:
```
rsync --dry-run -ave \
ssh [biocadmin\@malbec1](mailto:biocadmin@malbec1){.email}:PACKAGES/3.6/data/annotation/ .
```
This line looked like the following in the .md version:
```
rsync --dry-run -ave ssh biocadmin@malbec1:PACKAGES/3.6/data/annotation/ .
```

The second example is line 120 and 121 in the current version:
```
ssh [ubuntu\@master.biocondcutor.org](mailto:ubuntu@master.biocondcutor.org){.email} \
sudo su - webadmin cd /extra/www/bioc/packages/3.14/data/annotation
```
This is line 74-76 in the .md file:
```
ssh ubuntu@master.biocondcutor.org
sudo su - webadmin
cd /extra/www/bioc/packages/3.14/data/annotation
```
This second example it's crucial to do each line as a step when in the .Rmd file the `sudo` and `cd` commands look to be all one, which results in an error.

**Comment by LiNk-NY** [comment]
Thanks Kayla, that's helpful. I'm not sure how those tags were added. I have updated the commands in the vignette.

**Comment by LiNk-NY** [comment]
Feel free to re-open if the issue hasn't been solved. Thanks.
